/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworld_ReserveWrapper */

#ifndef _Included_com_rtes_taskmon_ReserveWrapper
#define _Included_com_rtes_taskmon_ReserveWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rtes_taskmon_ReserveWrapper
 * Method:    setreserve
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_rtes_taskmon_ReserveWrapper_setreserve
  (JNIEnv *, jclass, jint, jint, jlong, jint, jlong, jint);

/*
 * Class:     com_rtes_taskmon_ReserveWrapper
 * Method:    cancelreserve
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rtes_taskmon_ReserveWrapper_cancelreserve
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
